spring:
  application:
    name: Videos4All
  datasource:
    url: jdbc:postgresql://localhost:5432/Videos4All
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

